# Generated by Django 3.1.1 on 2020-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node1', models.CharField(max_length=10)),
                ('node2', models.CharField(max_length=10)),
                ('edge', models.CharField(max_length=10)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=10)),
            ],
        ),
    ]
