# Generated by Django 3.1.1 on 2020-09-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edges',
            name='node1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_nodes', to='map.nodes'),
        ),
        migrations.AlterField(
            model_name='edges',
            name='node2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.nodes'),
        ),
    ]
