# Generated by Django 3.1.1 on 2020-10-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200906_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=300)),
                ('cost', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('people', models.IntegerField()),
                ('date', models.CharField(max_length=300)),
            ],
        ),
    ]
