# Generated by Django 3.1.1 on 2020-10-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20201026_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
    ]
