# Generated by Django 3.1.1 on 2020-10-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20201026_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, default='media/images/events/default.jpeg', help_text='Event Photo', null=True, upload_to='media/images/events/'),
        ),
    ]
