# Generated by Django 3.1.1 on 2020-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
